Fix short trajectory plotting
shirtsgroup/physical_validation pull request #77
Opened 2020-12-09 18:52 UTC by ptmerz

## Description
Histogram plotting was requiring 150 data points per bin, and didn't prevent having zero bins if the trajectory was shorter. Fixed by explaining the reasoning in a warning, and proceeding with a minimum number of bins if trajectory is shorter.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [x] Fixes #76

## Status
- [x] Ready to go

2020-12-11 11:18 UTC, SimonBoothroyd requested changes
LGTM with just a small change!

2020-12-11 11:18 UTC, SimonBoothroyd commented on physical_validation/util/kinetic_energy.py
> +                "hist": max(5, num_hist_bins),
```suggestion
                "hist": max(min_num_hist_bins, num_hist_bins),
```

2020-12-11 15:54 UTC, ptmerz commented
Good catch, thanks!

2021-01-29 07:17 UTC, ptmerz commented
@SimonBoothroyd, would you have a moment to re-review that? Thanks!

2021-01-29 09:45 UTC, SimonBoothroyd approved these changes
LGTM!

2021-02-15 03:39 UTC, merged